### ISSUE TITLE
missing "http://" in url=

### ISSUE THREAD

**Issue by smuckola** [zhaofengli/refill#19]
When it processes a bare Internet Archive url, it fails to include "http://" on the "url=" segment.

For example:
<pre><ref>https://web.archive.org/web/20141114155440/www.allgame.com/game.php?id=53092</ref></pre>
becomes this:
<pre><ref>{{cite web|url=www.allgame.com/game.php?id=53092|archiveurl=https://web.archive.org/web/20141114155440/www.allgame.com/game.php?id=53092|title=Street Fighter II Turbo: Hyper Fighting [Virtual Console]|author=Rovi Corporation|archivedate=14 November 2014|publisher=}}</ref></pre>

And this will yield an error when rendered at the bottom of the article.

**Comment by zhaofengli** [comment]
Nice catch! Fixed! :+1:
