### ISSUE TITLE
Update localisation endpoint

### ISSUE THREAD

**Issue by siebrand** [zhaofengli/refill#24]
App is now integrated in translatewiki.net. https://tools.wmflabs.org/refill/index.php mentions "Please help translate reFill into your language by joining the Transifex project." Using multiple online localisation platforms may cause conflicts. Please update this.

**Comment by siebrand** [comment]
See https://translatewiki.net/wiki/Special:MessageGroupStats/int-refill for stats

**Comment by zhaofengli** [comment]
Good point! Will do that later.

**Comment by zhaofengli** [comment]
Hi @siebrand. Sorry for the terrible delay, but I've been very busy recently. I've updated [the banners](https://github.com/zhaofengli/refill-labsconf/commit/25b6f3481de29c8b32647c419f9480b072fd68a7) and [README.md](https://github.com/zhaofengli/refill/commit/fae0ce480c15eb80137b4ae7c220e0175c1935c4) to reflect the change. I'm also working to migrate new translations made on Transifex and close the old project. Thanks for your help!
