### ISSUE TITLE
Archive.is and long form URLs

### ISSUE THREAD

**Issue by greencardamom** [zhaofengli/refill#33]
Archive.is URLs should be in long form. This was decided by a community consensus RfC:

https://en.wikipedia.org/wiki/Wikipedia_talk:Using_archive.is#RfC:_Should_we_use_short_or_long_format_URLs.3F

For example in this reFill edit:

https://en.wikipedia.org/w/index.php?title=Deaths_in_June_2008&type=revision&diff=765095371&oldid=764757790

Search for "http://archive.is/20120723102538" .. note how it converted from long -> short form.

If reFill doesn't want to convert short -> long that is OK but it should not convert long -> short per the RfC. WaybackMedic and IABot are working to convert everything to long.

**Comment by zhaofengli** [comment]
Done on the [test version](https://tools.wmflabs.org/refill/test) and appears to work in [this edit](https://en.wikipedia.org/w/index.php?title=User:Zhaofeng_Li/sandbox&diff=775568429&oldid=775568345). Could you test?

**Comment by greencardamom** [comment]
Here is a testcases page diff for the 20-some archive services:

https://en.wikipedia.org/w/index.php?title=Wikipedia%3AList_of_web_archives_on_Wikipedia%2Ftestcases&type=revision&diff=776449704&oldid=776404365

Generally looks good. There are a couple unmodified links because the URL is unreachable or blacklisted.

Two problems with archive.is

1. Could you remove the formatting characters from the timestamp? For example

http://archive.fo/2013.05.01-162330 -> http://archive.fo/20130501162330

This is how the other bots on Enwiki format timestamps and is consistent with other archive services (see testcases page). Archive.is has quirky formatting options. 

2. It changed https to http. For some reason the <input id="SHARE_LONGLINK" ..> converts to http but needs to convert back to https. Even if the original wasn't https it's OK to convert to https it will save bot work later.

**Comment by zhaofengli** [comment]
How do you like https://en.wikipedia.org/w/index.php?title=User:Zhaofeng_Li/sandbox&diff=776593844&oldid=776593643 ?

**Comment by greencardamom** [comment]
Much better, thank you. One more thing it could have |deadurl=yes which is somewhat redundant in this case but generally a good idea to provide it when adding archives to CS1|2 templates.

**Comment by zhaofengli** [comment]
Okay, done in 6b3af2579f56026113fb11aa93462b4b0d66adbf ([Example edit](https://en.wikipedia.org/w/index.php?title=User:Zhaofeng_Li/sandbox&diff=777614086&oldid=777613987)).

**Comment by greencardamom** [comment]
Thanks! Looks really good.
