### ISSUE TITLE
Refill deletes AFCP decline messages

### ISSUE THREAD

**Issue by notvenom** [zhaofengli/refill#38]
When I declined (https://en.wikipedia.org/w/index.php?title=Draft%3ABOLA_DRMOLOVA&type=revision&diff=788642702&oldid=788642541)  some days ago, I fixed the references after that I declined it (non-notable). When i looked at the revision, I noticed that this tool deletes the original decline message (for some kind of reason). Is the author of this tool aware of it? Regards, Marcos-R, shadowowl.

**Comment by zhaofengli** [comment]
Replied on https://en.wikipedia.org/wiki/User_talk:Zhaofeng_Li/reFill#ReFill_deletes_decline_messages_when_used_in_Draft_after_declining_a_draft.
