### ISSUE TITLE
The zh_hant translation isn't working

### ISSUE THREAD

**Issue by alexanderlime** [zhaofengli/refill#6]
I tried switching the language to zh_hant, zh_tw and zh_hk but the website showed Simplified Chinese only.

**Comment by zhaofengli** [comment]
Oops, I forgot to tell that it's only available on [the test version](https://tools.wmflabs.org/refill/test/?userlang=zh-hant) at the moment. It will become available on the stable one when it's on the `labs-stable` branch, after some testing.

**Comment by zhaofengli** [comment]
I've merged the changes into the `labs-stable` branch. They should show up now. :)

**Comment by alexanderlime** [comment]
thx :)
